server{
    listen 8080;
    listen [::]:8080;

    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    access_log /var/log/nginx/phuong/access.log;
    error_log /var/log/nginx/phuong/error.log;

    location / {
        try_files $uri $uri/ =404;
    }
}